services:
  app:
    #    build: . #через dockerfile
    image: library:latest #через jib
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/jamtime
      - SPRING_DATASOURCE_USERNAME=jamuser
      - SPRING_DATASOURCE_PASSWORD=jampass
  #      SPRING_DATA_MONGODB_URI: ${SPRING_DATA_MONGODB_URI}

  postgres:
    image: postgres:16
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: jamtime
      POSTGRES_USER: jamuser
      POSTGRES_PASSWORD: jampass

volumes:
  jamTime_data:
