spring:
  datasource:
    url: jdbc:h2:mem:jamtime_db;
    driverClassName: org.h2.Driver
    username: sa
    password: sa
  #  sql:
  #    init:
  #      mode: always
  #      data-locations: data.sql
  #      schema-locations: schema.sql
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate #не будем автоматически генерировать сущности
    #      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console

  liquibase:
    enabled: true
    parameters:
      csv.allowQuotedData: true
    contexts: dev
  output:
    ansi:
      enabled: always
  shell:
    interactive:
      enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE