spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jamtime
    driverClassName: org.postgresql.Driver
    username: jamuser
    password: jampass
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: validate #не будем автоматически генерировать сущности
#      ddl-auto: update #будет автоматически генерировать сущности
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    enabled: true
    parameters:
      csv.allowQuotedData: true
    contexts: dev
  output:
    ansi:
      enabled: always
  shell:
    interactive:
      enabled: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    operations-sorter: method
    tags-sorter: alpha
    display-request-duration: true

jwt:
  secret: "SuperSecretJamKey2025!jabjbedjahwdjahwbdjhwbdjahbjwdbh"  #сменить вынести в ENV
  expiration: 3600000  # 1 час
#  expiration: 30000  # 30 сек

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    sql: debug